model_list:
  # GPT-4o
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: openai/gpt-4o-2024-08-06
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  - model_name: gpt-4o-2024-11-20
    litellm_params:
      model: openai/gpt-4o-2024-11-20
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  # GPT-4.1
  - model_name: gpt-4.1-2025-04-14
    litellm_params:
      model: openai/gpt-4.1-2025-04-14
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  - model_name: gpt-4.1-mini-2025-04-14
    litellm_params:
      model: openai/gpt-4.1-mini-2025-04-14
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  - model_name: gpt-4.1-nano-2025-04-14
    litellm_params:
      model: openai/gpt-4.1-nano-2025-04-14
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  # o4-mini
  - model_name: o4-mini-2025-04-16
    litellm_params:
      model: openai/o4-mini-2025-04-16
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  # o3
  - model_name: o3-2025-04-16
    litellm_params:
      model: openai/o3-2025-04-16
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  # GPT-5
  - model_name: gpt-5-2025-08-07
    litellm_params:
      model: openai/gpt-5-2025-08-07
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  - model_name: gpt-5-nano-2025-08-07
    litellm_params:
      model: openai/gpt-5-nano-2025-08-07
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  - model_name: gpt-5-mini-2025-08-07
    litellm_params:
      model: openai/gpt-5-mini-2025-08-07
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: "os.environ/OPENAI_BASE_URL"
  # Claude 4
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: claude-opus-4-1-20250805
      api_key: "os.environ/ANTHROPIC_API_KEY" 
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: claude-sonnet-4-20250514
      api_key: "os.environ/ANTHROPIC_API_KEY" 
  # Gemini 2.5
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini-2.5-pro
      api_key: "os.environ/GOOGLE_API_KEY"
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GOOGLE_API_KEY"
  - model_name: gemini-2.5-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: "os.environ/GOOGLE_API_KEY"

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  max_parallel_requests: 20
  global_max_parallel_requests: 20
  
litellm_settings:
  request_timeout: 60
  drop_params: true